apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: app
    repoURL: https://github.com/vinhnv1/crawler-k8s
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
