apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  # Note: argocd here "2"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: run
    spec:
      restartPolicy: OnFailure
      containers:
        - image: vinhdev1/example-crawler-migrate
          name: migrate
          command:
          - "/app/run"
          - "migrate"
          env:
            - name: POSTGRES_DNS
              value: postgres://crawler:do02lab@postgres-0.postgres-headless:5432/crawler?sslmode=disable
